
name: cp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip
  - pandas
  - requests
  - numpy
  - bs4
  - pip:
    - slack_sdk
    - google-cloud
    - google-cloud-storage
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - pandas-ods-reader
    - ratelimit
    - backoff
    - gcsfs
    - geopandas
    - osmnx
    - contextily
    - google-api-python-client
